@WebApi_HostAddress = https://localhost:5002


### GET USERS - I DONT THINK WE SHOULD USE THIS
GET {{WebApi_HostAddress}}/api/users/paged?
Authorization: Kat

### GET LOGGED IN USER
GET {{WebApi_HostAddress}}/api/users
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmljbGFzIiwiZXhwIjoxNzM0MDk2MTczfQ.O3otQEE7Ks9pH_j98QkTT__pEx24AT2uJFU3kE6LIhjp3bSefrptuy_DFY2IufEp0s8PeXg6lR2tcLjMk0bJZg


### CREATE USER
POST {{WebApi_HostAddress}}/api/users
Content-Type: application/json
{
    "username": "Akash",
    "password": "123",
    "email": "Akash@gmail.com",
    "birthday": "1998-06-04",
    "phonenumber": "25123456"
}

### UPDATE USER
PUT {{WebApi_HostAddress}}/api/users/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmljbGFzIiwiZXhwIjoxNzM0MTAxMTQzfQ.nlPnAsJeCHacfKw9tlEQziTxrivCCj_3KiFhrJLQy6VYNZgWGbVrVWJuli5gv2XV2um1EDldY0v4jnLwNoEFkQ

{
    "email": "TESTESTEEST@gmail.com",
    "birthday": "1998-01-01",
    "phonenumber": "25123456"
}

### - LOG IN
PUT {{WebApi_HostAddress}}/api/users/login
Content-Type: application/json
{
    "username": "Akash",
    "password": "123"
}

### - DELETE USER
DELETE {{WebApi_HostAddress}}/api/users
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg0OTY2fQ.C6PQea9DVAFYfUVzfMOZNFaKnDCYekRsGM6SmCrGNhqNKyD6wbIWDAyVb8GAY5NX2xbJVNey936CxW3rlqvgbg



### - GET TITLES PAGED
GET {{WebApi_HostAddress}}/api/titles?page=10&pagesize=25

### - GET TITLES PAGED DEFAULT PAGING
GET {{WebApi_HostAddress}}/api/titles
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVEVTVEVSIiwiZXhwIjoxNzM0MDc4MDY0fQ.axsiOOy97jOxq8I1uwg5UgkmjjdspBCoqZvmIZMYeIMcTaNZdMVfkRHuH5pTVUdJJr8edRd9rEINKpohgCOE6A

### - GET SINGLE TITLE
GET {{WebApi_HostAddress}}/api/titles/tt26693752
Accept: application/json




### - GET NAMES PAGED 
GET {{WebApi_HostAddress}}/api/names?page=10&pagesize=25
Accept: application/json

### - GET NAMES PAGED DEFAULT PAGING
GET {{WebApi_HostAddress}}/api/names
Accept: application/json


### - GET SINGLE NAME
GET {{WebApi_HostAddress}}/api/names/nm0000035
Accept: application/json




### - GET SINGLE BOOKMARK FROM THE LOGGED IN USER - DONT THINK WE ARE GONNA USE THIS ONE
GET {{WebApi_HostAddress}}/api/bookmarknames/nm0000005
Authorization: Kat

### - GET PAGED BOOKMARKS OF LOGGED IN USER
GET {{WebApi_HostAddress}}/api/bookmarknames
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWthc2giLCJleHAiOjE3MzQxMDE2Mjh9.0U4mcMU9rdUiCdlKS2_v6-t31ftQORXyWDUPLCxb_MV967v0m0qoV40SkHYqOu2YJ3kY4GWW80G53U4y1EmOAg

### - CREATE BOOKMARK
POST {{WebApi_HostAddress}}/api/bookmarknames
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWthc2giLCJleHAiOjE3MzQxMDE2Mjh9.0U4mcMU9rdUiCdlKS2_v6-t31ftQORXyWDUPLCxb_MV967v0m0qoV40SkHYqOu2YJ3kY4GWW80G53U4y1EmOAg
{
    "nameid": "nm0000114"
}

### - DELETE BOOKMARK
DELETE {{WebApi_HostAddress}}/api/bookmarknames/nm0000100
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg1ODIwfQ.EW4eCNc_FfqKxC8JtCH0Tvy5oM0KGY0MTQYYLDsf4NImhE2_UU8zntyk1gt_0RXA61wPri4dPC_5JCB5z9aA6A


### - GET SINGLE BOOKMARK FROM THE LOGGED IN USER - DONT THINK WE ARE GONNA USE THIS ONE
GET {{WebApi_HostAddress}}/api/bookmarktitles/tt20854604
Authorization: Kat

### - GET PAGED BOOKMARKS OF LOGGED IN USER
GET {{WebApi_HostAddress}}/api/bookmarktitles
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg2MjI1fQ.eBZLDPc6T0XSA7rZ0kit6frIhfu_VXJ6vqJjZD2uOweh3ExmtbbJmOX8tbvY5nqUbIFYYwHTY7IFaP1aPLb3mw

### - CREATE BOOKMARK
POST {{WebApi_HostAddress}}/api/bookmarktitles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg2MjI1fQ.eBZLDPc6T0XSA7rZ0kit6frIhfu_VXJ6vqJjZD2uOweh3ExmtbbJmOX8tbvY5nqUbIFYYwHTY7IFaP1aPLb3mw
{
    "titleid": "tt26693752"
}

### - DELETE BOOKMARK
DELETE {{WebApi_HostAddress}}/api/bookmarktitles/tt26693752
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg2MjI1fQ.eBZLDPc6T0XSA7rZ0kit6frIhfu_VXJ6vqJjZD2uOweh3ExmtbbJmOX8tbvY5nqUbIFYYwHTY7IFaP1aPLb3mw


### - GET SINGLE RATING FROM THE LOGGED IN USER - DONT THINK WE ARE GONNA USE THIS ONE
GET {{WebApi_HostAddress}}/api/userratings/tt21931780
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWthc2giLCJleHAiOjE3MzQxMDE2Mjh9.0U4mcMU9rdUiCdlKS2_v6-t31ftQORXyWDUPLCxb_MV967v0m0qoV40SkHYqOu2YJ3kY4GWW80G53U4y1EmOAg

### - GET PAGED RATINGS OF LOGGED IN USER
GET {{WebApi_HostAddress}}/api/userratings
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWthc2giLCJleHAiOjE3MzQxMDE2Mjh9.0U4mcMU9rdUiCdlKS2_v6-t31ftQORXyWDUPLCxb_MV967v0m0qoV40SkHYqOu2YJ3kY4GWW80G53U4y1EmOAg

### - CREATE RATING
POST {{WebApi_HostAddress}}/api/userratings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWthc2giLCJleHAiOjE3MzQxMDE2Mjh9.0U4mcMU9rdUiCdlKS2_v6-t31ftQORXyWDUPLCxb_MV967v0m0qoV40SkHYqOu2YJ3kY4GWW80G53U4y1EmOAg
{
    "titleid": "tt21931780",
    "rating": 8
}

### - DELETE RATING
DELETE {{WebApi_HostAddress}}/api/userratings/tt21931780
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg4NTA2fQ.oIDgLbg8EQU7cFw8n1Vzi96NUt3V77SsmRz2-QbV_n59fA2_QhxhPcjCA6J-JGOvzcAyTyR51v77hA0VIVcSsw

### - UPDATE RATING
PUT {{WebApi_HostAddress}}/api/userratings/tt21931780
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg4NTA2fQ.oIDgLbg8EQU7cFw8n1Vzi96NUt3V77SsmRz2-QbV_n59fA2_QhxhPcjCA6J-JGOvzcAyTyR51v77hA0VIVcSsw
{
  "rating": 8
}


### - GET SINGLE SEARCH BY LOGGED IN USER
GET {{WebApi_HostAddress}}/api/searches/11
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg2NjIyfQ.G9nthsbJjS04yH0kRAqumjf79asikOlVKOFAUDvToOdnQMkJgNZX2mgOaMYma1Al_NNQ2iZB5nR-C_sdDiU6Xw

### - GET ALL SEARCHES BY LOGGED IN USER
GET {{WebApi_HostAddress}}/api/searches
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg2NjIyfQ.G9nthsbJjS04yH0kRAqumjf79asikOlVKOFAUDvToOdnQMkJgNZX2mgOaMYma1Al_NNQ2iZB5nR-C_sdDiU6Xw

### - CREATE SEARCH
POST {{WebApi_HostAddress}}/api/searches
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg2NjIyfQ.G9nthsbJjS04yH0kRAqumjf79asikOlVKOFAUDvToOdnQMkJgNZX2mgOaMYma1Al_NNQ2iZB5nR-C_sdDiU6Xw
{
    "content": "hej"
}

### - DELETE SEARCH
DELETE {{WebApi_HostAddress}}/api/searches/10
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg2NjIyfQ.G9nthsbJjS04yH0kRAqumjf79asikOlVKOFAUDvToOdnQMkJgNZX2mgOaMYma1Al_NNQ2iZB5nR-C_sdDiU6Xw
