@WebApi_HostAddress = https://localhost:5002



### GET LOGGED IN USER
GET {{WebApi_HostAddress}}/api/users
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw


### CREATE USER
POST {{WebApi_HostAddress}}/api/users
Content-Type: application/json
{
    "username": "NewUser",
    "password": "123",
    "email": "NewUser@gmail.com",
    "birthday": "1998-06-04",
    "phonenumber": "25123456"
}

### UPDATE USER
PUT {{WebApi_HostAddress}}/api/users/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw

{
    "email": "NewMail.com",
    "birthday": "1998-01-01",
    "phonenumber": "25123456"
}

### - LOG IN
PUT {{WebApi_HostAddress}}/api/users/login
Content-Type: application/json
{
    "username": "NewUser",
    "password": "123"
}

### - DELETE USER
DELETE {{WebApi_HostAddress}}/api/users
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg0OTY2fQ.C6PQea9DVAFYfUVzfMOZNFaKnDCYekRsGM6SmCrGNhqNKyD6wbIWDAyVb8GAY5NX2xbJVNey936CxW3rlqvgbg





### - GET Movies PAGED
GET {{WebApi_HostAddress}}/api/titles/movies/

### - GET TVSERIES PAGED
GET {{WebApi_HostAddress}}/api/titles/tvseries

### - GET SINGLE TITLE
GET {{WebApi_HostAddress}}/api/titles/tt26693752
Accept: application/json




### - GET NAMES PAGED 
GET {{WebApi_HostAddress}}/api/names?page=10&pagesize=25
Accept: application/json

### - GET NAMES PAGED DEFAULT PAGING
GET {{WebApi_HostAddress}}/api/names
Accept: application/json


### - GET SINGLE NAME
GET {{WebApi_HostAddress}}/api/names/nm0000035
Accept: application/json




### - GET PAGED BOOKMARKS OF LOGGED IN USER
GET {{WebApi_HostAddress}}/api/bookmarknames
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw

### - CREATE BOOKMARK
POST {{WebApi_HostAddress}}/api/bookmarknames
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw
{
    "nameid": "nm0001355"
}

### - DELETE BOOKMARK
DELETE {{WebApi_HostAddress}}/api/bookmarknames/nm0001355
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw




### - GET PAGED BOOKMARKS OF LOGGED IN USER
GET {{WebApi_HostAddress}}/api/bookmarktitles
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw

### - CREATE BOOKMARK
POST {{WebApi_HostAddress}}/api/bookmarktitles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw
{
    "titleid": "tt26693752"
}

### - DELETE BOOKMARK
DELETE {{WebApi_HostAddress}}/api/bookmarktitles/tt26693752
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw





### - GET PAGED RATINGS OF LOGGED IN USER
GET {{WebApi_HostAddress}}/api/userratings
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw

### - CREATE RATING
POST {{WebApi_HostAddress}}/api/userratings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw
{
    "titleid": "tt21931780",
    "rating": 8
}

### - DELETE RATING
DELETE {{WebApi_HostAddress}}/api/userratings/tt21931780
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw

### - UPDATE RATING
PUT {{WebApi_HostAddress}}/api/userratings/tt21931780
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw
{
  "rating": 8
}



### - GET ALL SEARCHES BY LOGGED IN USER
GET {{WebApi_HostAddress}}/api/searches
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw

### - CREATE SEARCH
POST {{WebApi_HostAddress}}/api/searches
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTmV3VXNlciIsImV4cCI6MTczNDE4MjIxN30._IZIbzm_Xe8kvBVTUeTd8-eDqLWQW16AZ-6bzX-0sDEGK7s2MVlNVl2WKlNWTRncpubkRs3YiIjbV9TG6OVSUw
{
    "content": "helloworld"
}

### - DELETE SEARCH
DELETE {{WebApi_HostAddress}}/api/searches/10
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGlha2F0IiwiZXhwIjoxNzM0MDg2NjIyfQ.G9nthsbJjS04yH0kRAqumjf79asikOlVKOFAUDvToOdnQMkJgNZX2mgOaMYma1Al_NNQ2iZB5nR-C_sdDiU6Xw
